spring.application.name=BootJPAProj08-MultiDBInteraction

#oracle DB related datasource
oracle.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
oracle.datasource.jdbc-url=jdbc:oracle:thin:@localhost:1521:orcl
oracle.datasource.username=system
oracle.datasource.password=******

#MySQL DB related datasource
mysql.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mysql.datasource.jdbc-url=jdbc:mysql:///ntspbms718db
mysql.datasource.username=root
mysql.datasource.password=*******

#JPA-Hibernate properties
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
